# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true   # enable all by default
MD007:          # unordered list indentation
  indent: 2
MD013: false    # do not validate line length
MD014: false    # allow $ before command output
MD029:          # ordered list prefix, use all ones
  style: "one"
MD033:          # allow html tags
  allowed_elements:
    - b
    - div
    - h1
    - img
    - p
    - picture
    - source
MD041: false    # the first line in readme is not a MD header
